#!/usr/bin/env python3
"""Generate typed DataKey<T> handles from runtime_snapshot.json descriptors."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


TYPE_MAP = {
    "string": "string",
    "string_array": "string",
    "int": "int",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "vector2": "Godot.Vector2",
    "enum": "string",
    "modifier_list": "string",
    "object_ref": "string",
}


def to_identifier(stable_key: str) -> str:
    parts = re.split(r"[^0-9A-Za-z_]+", stable_key)
    raw = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if not raw:
        raise ValueError(f"invalid stable key: {stable_key!r}")
    if raw[0].isdigit():
        raw = "_" + raw
    return raw


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate-data-key-handles.py <runtime_snapshot.json> <output.cs>", file=sys.stderr)
        return 2

    snapshot_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    snapshot = json.loads(snapshot_path.read_text())
    descriptors = sorted(snapshot.get("descriptors", []), key=lambda item: item["stableKey"])

    seen_identifiers: set[str] = set()
    lines = [
        "// <auto-generated />",
        "// Generated from DataOS/Snapshots/runtime_snapshot.json. Do not add defaults, ranges, computed policy or modifier policy here.",
        "",
        "/// <summary>",
        "/// Descriptor-generated typed DataKey handles.",
        "/// </summary>",
        "public static class GeneratedDataKey",
        "{",
    ]

    for descriptor in descriptors:
        stable_key = descriptor["stableKey"]
        identifier = to_identifier(stable_key)
        if identifier in seen_identifiers:
            raise ValueError(f"duplicate generated identifier: {identifier} from {stable_key}")
        seen_identifiers.add(identifier)

        value_type = descriptor.get("valueType", "")
        runtime_type_id = descriptor.get("runtimeTypeId", "")
        csharp_type = runtime_type_id if value_type == "enum" and runtime_type_id else TYPE_MAP.get(value_type)
        if csharp_type is None:
            raise ValueError(f"unsupported descriptor valueType: {stable_key} -> {value_type}")

        escaped_key = stable_key.replace("\\", "\\\\").replace('"', '\\"')
        lines.extend(
            [
                "    /// <summary>",
                f"    /// {stable_key}",
                "    /// </summary>",
                f"    public static readonly DataKey<{csharp_type}> {identifier} = new(\"{escaped_key}\");",
                "",
            ]
        )

    lines.append("}")
    lines.extend(
        [
            "",
            "/// <summary>",
            "/// Compatibility aliases for callsites that still use DataKey.Xxx during migration.",
            "/// </summary>",
            "public static partial class DataKey",
            "{",
        ]
    )

    for descriptor in descriptors:
        stable_key = descriptor["stableKey"]
        identifier = to_identifier(stable_key)
        value_type = descriptor.get("valueType", "")
        runtime_type_id = descriptor.get("runtimeTypeId", "")
        csharp_type = runtime_type_id if value_type == "enum" and runtime_type_id else TYPE_MAP.get(value_type)
        if csharp_type is None:
            raise ValueError(f"unsupported descriptor valueType: {stable_key} -> {value_type}")

        lines.extend(
            [
                "    /// <summary>",
                f"    /// {stable_key}",
                "    /// </summary>",
                f"    public static readonly global::DataKey<{csharp_type}> {identifier} = GeneratedDataKey.{identifier};",
                "",
            ]
        )

    lines.append("}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
